### PR TITLE
Add material library theme

### PR DESCRIPTION
**Pull request by theantariksha**
#55 

Please someone else also test if possible

i got the images off https://www.svgrepo.com/svg/384728/rounded-square-arrow-indicator-right
need to sure if there are ~~any licensing restrictions~~ . Update: it's free to reuse and share

### CODE REVIEW

**Review by T-melon — APPROVED** [review]
Oh! Sorry I didn't have enough time to revise last week, this looks quite good! Are there any other additional tasks I can work on?

**Comment by theantariksha** [comment]
> Oh! Sorry I didn't have enough time to revise last week, this looks quite good! Are there any other additional tasks I can work on?

no worries, did you get a chance to test this change? I did test it once quickly, but I was hoping someone else could also just in case

**Comment by T-melon** [comment]
> > Oh! Sorry I didn't have enough time to revise last week, this looks quite good! Are there any other additional tasks I can work on?
> 
> no worries, did you get a chance to test this change? I did test it once quickly, but I was hoping someone else could also just in case

I didn't notice any changes (such as the icon); maybe it's an issue with my simulator?

**Comment by theantariksha** [comment]
> > > Oh! Sorry I didn't have enough time to revise last week, this looks quite good! Are there any other additional tasks I can work on?
> > 
> > 
> > no worries, did you get a chance to test this change? I did test it once quickly, but I was hoping someone else could also just in case
> 
> I didn't notice any changes (such as the icon); maybe it's an issue with my simulator?

hmm, I'm not sure, the icons should be visible in the text message view screens to switch between prev and next messages. the general theme and button designs should also look different from earlier.
we can check it tomorrow

**Comment by jup023** [comment]
I've noticed that the color of the icons changes from purple to black instantly when there's no message available. Is that intended or a bug?

**Comment by theantariksha** [comment]
> I've noticed that the color of the icons changes from purple to black instantly when there's no message available. Is that intended or a bug?

i think that's because the buttons are disabled now when there are no messages in that direction

**Pull request merged**
